### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by clinnen** [bcm-uga/pcadapt#16]
Hello,
I would like to try out your program, but when I attempted installing it from github, it fails. Attached is a text file with the installation warnings and errors. Any advice you have would be greatly appreciated.
Thank you,
Catherine
[Installation-errors.txt](https://github.com/bcm-uga/pcadapt/files/2138918/Installation-errors.txt)

**Comment by privefl** [comment]
Your issue is **library not found for -lgfortran**, a known issue when installing package {RcppArmadillo} on Mac.

Please see see [this blog post](http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/) for a solution.

**Comment by mblumuga** [comment]
@clinnen Which version of pcadapt did you try to install?

**Comment by clinnen** [comment]
Thanks for getting back to me. I attempted to install a couple of different versions (all with similar outcomes). The errors attached above occurred when I attempted to install whatever is on github ("devtools::install_github("bcm-uga/pcadapt"). I also attempted to install the latest version that was archived on CRAN. Is there a particular version I should be using that is not one of these? I will also investigate the RcppArmadillo issue noted above.
Thanks!

**Comment by clinnen** [comment]
I just followed the advice posted by @privefl and it worked like a charm. But if this is the wrong version of pcadapt, please let me know and I'll reinstall.
Thanks!

**Comment by mblumuga** [comment]
You can now install the main version on github using devtools::install_github("bcm-uga/pcadapt"). The modification of @privefl for pooled-seq data with n=2 is now included in the master branch of pcadapt.

**Comment by clinnen** [comment]
Thanks!
