### ISSUE TITLE
Formatting plots

### ISSUE THREAD

**Issue by fvaux** [bcm-uga/pcadapt#19]
Hi, I have a pretty simple question: is there a way to plot the PCAdapt PCA ordination plots with increased point sizes, different labels and individual labels?

The plot seems to be produced using the base function in R, but things like pch= and cex= do not seem to modify the plot. Is there a way to change these features while plotting in PCAdapt?

Thanks

**Comment by privefl** [comment]
Which version do you use?
We have been using ggplot2 for a long time now.

If you want to make custom plots, I would suggest to make the plots from scratch with ggplot2 (or base R if you prefer).

**Comment by fvaux** [comment]
I am using pcadapt version 4.0.3.

I've also tried making PCA plots using adegenet, but the plots in pcadapt look better as the axes are labelled, and the plots are centered. 

It would be great if I could stick to using the pcadapt plots, but be able to increase the point sizes, use different symbols for each group, and add labels for individuals (i.e. sample numbers).

**Comment by privefl** [comment]
As I said, it's just ggplot2 plots; you could easily make them yourself.
If you share your pcadapt results and your groups, etc, and I can show you.

**Comment by mblumuga** [comment]
@aesculushippocastanum : If you send us a [reproducible R script](http://adv-r.had.co.nz/Reproducibility.html), we would be able to provide support and decide if changes are needed in the R packages.
