### ISSUE TITLE
Error in UseMethod("pcadapt") :    no applicable method for 'pcadapt' applied to an object of class "character"

### ISSUE THREAD

**Issue by Carol-Symbiomics** [bcm-uga/pcadapt#21]
Hello,

Recently, I've tried to use pcadapt but I have failed.
I used the same command that worked in the past without success.
I've either converted my vcf file into pcadapt format or read the vcf directly using the `read.pcadapt`

spis306pcadapt <- read.pcadapt("./pop.gen.analyses/spis.filterdDocent.filterrad.final.recode.vcf", type = "vcf")
test <- pcadapt("spis306pcadapt", K=20)

Error in UseMethod("pcadapt") : 
  no applicable method for 'pcadapt' applied to an object of class "character"

I don't know what is wrong, could you please assist?

Sincerely,

Carol

**Comment by privefl** [comment]
Don't use the quotes around `spis306pcadapt`.
