### ISSUE TITLE
Use warning instead of stop for argument deprecation

### ISSUE THREAD

**Issue by zkamvar** [bcm-uga/pcadapt#3]
In the [most recent commit][0], you deprecated the `output.filename` and `clean.files` parameters. By using `stop()` instead of `warning()`, old scripts will break if they specify a different output prefix or decide not to clean files. A warning would allow old scripts to still run with the new version and alert the users that the parameters would change in the future.

[0]: https://github.com/BioShock38/pcadapt/commit/ecbb15ef5ee7e329c4178d1eb7bc46334b442780#diff-fb22eb16310fd5cae4c80d07609c50ceR59

**Comment by keurcien** [comment]
Hi, you're totally right, thanks for the suggestion !
