### ISSUE TITLE
Is there a way to associate outliers with the populations they discriminate

### ISSUE THREAD

**Issue by Ella-Bowles** [bcm-uga/pcadapt#33]
Hello,

Is there a way to associate outliers with the populations that they discriminate? I can use get.pc to get the SNPs that associate with each PC, but if I have say seven populations and three separate on each axis, it is not possible using this function to figure out which SNPs differentiate each of the populations. One option is perhaps to run the analysis for only two populations, but in that case the outliers found will be pretty different, since PCA takes into account all the variation within and between all populations.

With thanks,

**Comment by mblumuga** [comment]
Your comment is right, get.pc will return the PC associated with a SNP, but if there are three separate pops on this axis, it is not possible to figure out in which population adaptation took place. Looking at allele frequencies in each pop might provide some additional clues.

**Comment by Ella-Bowles** [comment]
Thank you.
