### ISSUE TITLE
Customized ttile of figure

### ISSUE THREAD

**Issue by zillurbmb51** [bcm-uga/pcadapt#40]
Hello, I was trying to use pcadapt for my snp data. Is there any way to write a customized title of the pca plot. 
```
x1321 <- read.pcadapt(bed_r1321, type = "bed")
x1321 <- pcadapt(input = x1321, K = 20)
plot(x1321, option = "scores", pop = pop_code)
```
This give us a figure with a title 'Projection onto PC1 and PC2'. Is it possible to write/add other text as title of the figure. I have tried 'main', 'text', 'title' arguments but nothing works. Best, Zillur

**Comment by privefl** [comment]
This should give you a {ggplot2} object.
So, I believe you can use `plot(...) + ggtitle(<your_new_title>)`.

**Comment by zillurbmb51** [comment]
Thank you. It works!
