### ISSUE TITLE
can't display the histogram as the values are too high.

### ISSUE THREAD

**Issue by zillurbmb51** [bcm-uga/pcadapt#41]
Hello, I was trying make stats distribution plot for my snp data using pcadapt:
 `pl6=plot(xclinvar, option = "stat.distribution", threshold = 0.1)+ggtitle('P_clinvar hg38 17076 SNPs')`
And getting this:
`error in hist_plot(x, 1) : can't display the histogram as the values are too high.`
Other plots like pca, qq or manhattan works good for this data and stat.distribution also works for other data but error is only for this. Any help? Best, Zillur

**Comment by privefl** [comment]
Looking at the code, it means that you have X2 statistics larger than 10^5, which is apparently not possible.
```
> pchisq(1e5, df = 100, lower.tail = FALSE, log.p = TRUE)
[1] -49614.4
```

Can you provide a reproducible example?

**Comment by zillurbmb51** [comment]
Thank you. I am not sure how to reproduce this error because with same data other plots work perfectly. Here is my original data. 
[clinvar.maf5.indep0.1.bed.txt](https://github.com/bcm-uga/pcadapt/files/3665979/clinvar.maf5.indep0.1.bed.txt)
[clinvar.maf5.indep0.1.bim.txt](https://github.com/bcm-uga/pcadapt/files/3665980/clinvar.maf5.indep0.1.bim.txt)
[clinvar.maf5.indep0.1.fam.txt](https://github.com/bcm-uga/pcadapt/files/3665981/clinvar.maf5.indep0.1.fam.txt)

**Comment by privefl** [comment]
I removed the `.txt` extensions (why do you have them?)
This works for me:
```
library(pcadapt)
bed <- read.pcadapt("tmp-data/clinvar.maf5.indep0.1.bed", type = "bed")
xclinvar <- pcadapt(bed)
plot(xclinvar, option = "stat.distribution", threshold = 0.1) +
  ggplot2::ggtitle('P_clinvar hg38 17076 SNPs')
```
Note that you might want to change `K` and use LD clumping.

**Comment by zillurbmb51** [comment]
Thank you. The extensions are to upload here. Loading without K works. How can I use LD clumping? Best, ZIllur

**Comment by privefl** [comment]
There is a parameter for it. Also see the vignette.

**Comment by mblumuga** [comment]
To use LD clumping, you need to have dense enough data. If you work with radseq data, do not bother with LD clumping. The paragraph "F. Linkage Disequilibrium (LD) thinning" in the [vignette](https://cran.r-project.org/web/packages/pcadapt/vignettes/pcadapt.html) explains how to run the procedure.
