### ISSUE TITLE
Question about obtaining z-scores 

### ISSUE THREAD

**Issue by kfarleigh** [bcm-uga/pcadapt#42]
Hi,
I had a quick question about how you calculate z-scores. Specifically, I am stuck conceptually how we regress the SNP with the principal components and was wondering if you could explain that for me.
Thanks,
Keaka

**Comment by privefl** [comment]
Z-scores are just the product of regressing PC scores by genotypes, like standard linear GWAS.
So, basically, they are t-scores.
