### ISSUE TITLE
pcadapt() grabbing too many cores

### ISSUE THREAD

**Issue by standard-aaron** [bcm-uga/pcadapt#44]
I am running pcadapt() (the command) on our servers and (it looks like) it's trying to grab way too many cores simultaneously.

Is there any way to force down the max # of cores used by pcadapt? 

Thanks,
Aaron

_______

My script:

```
#!/usr/bin/env Rscript
library(pcadapt)
filename <- read.pcadapt(path_to_file, type = "bed")
x <- pcadapt(input = filename, K = 20)
```

**Comment by privefl** [comment]
Package pcadapt does not use any parallel code.
What version are you using?

**Comment by standard-aaron** [comment]
4.1.0

**Comment by privefl** [comment]
What is the output of `system.time(x <- pcadapt(input = filename, K = 20))`?

**Comment by privefl** [comment]
There might be some matrix computations that are run in parallel if you have some parallelized matrix library linked with R, but I'm not even sure there are in the code.

You can try to use `RhpcBLASctl::blas_set_num_threads(1)` before running pcadapt to use only one core for matrix computations.

**Comment by standard-aaron** [comment]
Yup, this solved the issue. I realize this is a pretty generic problem -- thanks so much for nonetheless helping solve it!
