### ISSUE TITLE
variant(s) have been discarded as they are not SNPs

### ISSUE THREAD

**Issue by tjmcgreevy** [bcm-uga/pcadapt#45]
Hello,

I am trying to use a .vcf produced using FreeBayes via the program dDocent (version dDocent 2.8.9) with the pcadapt program.  When I load the .vcf using:

filename <- read.pcadapt(path_to_file, type = "vcf")
filename
#
1171 variant(s) have been discarded as they are not SNPs.
Summary:
  
  - input file:				/Users/t.j.mcgreevy/Documents/Anole/dDocent/pcadapt/All_Anole_n259/All_Anole_n259_12_21_19.g5mac3mQ30dp3lowDP60_80mm_01maf_15mDP.FIL.HWE_01_90mm_maf01_thin100.recode.vcf
- output file:				/var/folders/t2/xjfv3fq532n5sxz80vnsjnj80000gn/T//RtmpSRCwcC/file4bf64096fbe.pcadapt

- number of individuals detected:	259
- number of loci detected:		7994

1,171 variants are removed from the file, but I do not know why these SNPs are being removed.  I have converted the .vcf with PLINK and loaded the file into pcadapt with all 7,994 SNPs retained, so I am not sure why the SNPs are being filtered.  I would just continue to use the output from the PLINK conversion, but the chromosome position number is not matching the original file so I would like to use my original .vcf to make sure I am removing the correct SNPs.

Attached are the first 172 lines from my file, it is too large to send.  Any help will be appreciated.

Sincerely,
T.J.

[All_Anole_n259_12_21_19.g5mac3mQ30dp3lowDP60_80mm_01maf_15mDP.FIL.HWE_01_90mm_maf01_thin100.recode.vcf.zip](https://github.com/bcm-uga/pcadapt/files/4188784/All_Anole_n259_12_21_19.g5mac3mQ30dp3lowDP60_80mm_01maf_15mDP.FIL.HWE_01_90mm_maf01_thin100.recode.vcf.zip)

**Comment by privefl** [comment]
I've gone through the code to understand what the vcf2pcadapt converter does.
This message likely means that you have variants with missing values only.

Please note that we don't maintain this converter anymore since pcadapt v4.
Please use PLINK instead for conversion (and quality control at the same time).
After conversion, you have information on variants in the 'bim' file.

**Comment by tjmcgreevy** [comment]
Hello,

Thank you for your response.

Sincerely,
T.J.
