### ISSUE TITLE
Great difference of outliers detection using same cutoffs pcadapt/OutFlanks

### ISSUE THREAD

**Issue by MaraRMinano** [bcm-uga/pcadapt#47]
Hi, 

I am running analyses of SNPs outlier detections with 2 different methods, PCAadapt and Outflanks based on Fst. My data set: 46 populations, 12,543 SNPs.
Using the same restriction criteria, I get 1 outlier using Outflanks and around 600 Using PCAadapt.
My populations present high population structure (2 different marked groups)

Does anyone know why this might be?

Thanks a lot in advance
I am new in this kind of analysis, so I apologize if I am not giving the correct info.
Cheers, 
Mara

![Screen Shot 2020-03-27 at 12 16 34 pm](https://user-images.githubusercontent.com/9059904/77711381-ed43d280-7024-11ea-9a4a-a1e7a381e9f5.png)
![Screen Shot 2020-03-27 at 12 15 32 pm](https://user-images.githubusercontent.com/9059904/77711458-32680480-7025-11ea-8d00-55cf4df145d7.png)

**Comment by privefl** [comment]
Your issue seems similar to other issues that have been reported here.
E.g. https://github.com/bcm-uga/pcadapt/issues/24, https://github.com/bcm-uga/pcadapt/issues/31 and https://github.com/bcm-uga/pcadapt/issues/39.
Have you looked at them?

Why do you have only 12K variants?

**Comment by MaraRMinano** [comment]
Hi,thanks for answe!
Yes I did. 
I extracted 12k SNPs after running pipeline in stacks. Those are my results using maf 0.05 as filter.

**Comment by privefl** [comment]
Note that (cf. other issues) pcadapt requires null variants (with no effect on population structure) to compute the Mahalanobis distance. Can you run it with more variants?

Also, is it possible that these 600 variants are true outliers if it is very easy to distinguish between your populations. Can you look at PC scores?
