### ISSUE TITLE
Feature request: Polyploid data

### ISSUE THREAD

**Issue by ahmaduaf** [bcm-uga/pcadapt#50]
Hello,

I was wondering if there is a possibility to use tetraploid data with Pca adapt?, I have genotype data where data is coded from 0 to 5 ( 0= 0 copy of reference alleles. vs 5 = 4 copies of reference alleles).
Thank you!

**Comment by privefl** [comment]
Have you tried with the matrix format?

**Comment by privefl** [comment]
Unfortunately, I don't have time to work on this.

Maybe it would possible to hack or modify the matrix format.

Possible hack: currently, missing values are represented by 3 internally. If you code your 3s as 2.999999, maybe it could work.
Possible implem: change the way we code NAs internally (e.g. as a parameter) and make sure the code is general enough to accept tetraploid data.

**Comment by ahmaduaf** [comment]
Hello, 
Thanks, I think, it would be possible to input data (as a matrix) as diploid by modifying the tetraploid genotype matrix (I have not tried it yet), but i am not sure if it would be the right way to treat the data.

**Comment by privefl** [comment]
I mean, in the matrix, you should be able to store other values than 0, 1, 2 and NA
