### ISSUE TITLE
Remove Outliers from data

### ISSUE THREAD

**Issue by kwojtusik** [bcm-uga/pcadapt#53]
Hello,

I've run PCadapt and have identified the outliers for my data set. How would I go about creating a list of those SNPs to use in VCFtools so that I can remove them for downstream analyses?

Apologies if this has been answered before, I could not find it in other issues. Thank you.

-Kris

**Comment by privefl** [comment]
I'm not sure where I can help you.

If you have identified the outliers (their indices), and have the SNP names stored somewhere, then you can write the subset of names to some file to be used by VCFtools (which I never used before but assume it works like PLINK).
