### ISSUE TITLE
SNPs thinning LD clumping

### ISSUE THREAD

**Issue by msalamon2** [bcm-uga/pcadapt#67]
Hi, 

I am applying pcadapt to a dataset of pool-seq whole genome sequencing for 12 populations (~50 million SNPs). I tried to apply SNPs thinning with the LD.clumping option, but I get the same number of SNPs with or without thinning (and identical results for loadings plot, screeplot etc). I tried with different window size and r2 threshold but it's always the same number of SNPs before and after thinning. Based on the results from another analysis, I am almost certain that there is LD in my dataset. Could this be because this option is not supported for pool-seq data ?

Thank you

**Comment by privefl** [comment]
Yes, I don't think this is supported.
You can't really infer LD with 12 population averages.
