### ISSUE TITLE
Allele frequency data can use in pcadapt?

### ISSUE THREAD

**Issue by HengLiang1993** [bcm-uga/pcadapt#79]
Hi
I am trying to use allele frequency to run the pcadapt.

I have a 180 samples from 18 population, and I want to check the outlier by the allele frequency in 18 population.
I do not kown if I use the allele frequency to replace the allele count (like lfmm file) as input file in pcadapt is ok?
my allele frequeny data is as this:

POS	Population1	Population2	Population3	Population4	Population5	Population6	Population7	Population8	Population9	Population10	Population11	Population12	Population13
2_8711_G	0	0	0	0	0.166667	0	0	0	0	0	0	0	0
2_8722_C	0	0	0	0	0	0	0.05	0	0.05	0	0	0	0
2_8726_T	0.357143	0	0.0555556	0	0	0	0	0	0	0	0	0	0
2_8736_A	0	0.142857	0	0.222222	0	0	0	0	0	0	0	0	0
2_8742_T	0.1	0.0714286	0	0	0	0.111111	0	0.0833333	0	0	0	0	0.222222
2_8748_T	0	0	0	0	0.25	0	0	0	0	0	0	0	0
2_8754_A	0	0	0	0	0	0	0	0	0	0	0	0	0
2_8765_A	0	0	0	0	0	0.0625	0.05	0	0.05	0.0714286	0	0.0625	0
2_8773_T	0	0	0	0	0	0.125	0	0	0	0	0	0	0
2_8776_T	0	0	0	0	0	0	0	0	0	0	0	0	0
2_8778_T	0	0	0	0	0.25	0.0625	0.05	0	0.05	0	0	0.125	0
2_8779_T	0.125	0	0.0555556	0	0	0	0	0	0	0	0.277778	0	0.222222
2_8780_T	0.1	0	0	0	0	0	0.05	0	0.05	0	0	0.3125	0
2_8784_T	0	0	0	0	0.1	0.0555556	0.05	0	0.05	0	0.166667	0	0
 
Best

Heng

**Comment by privefl** [comment]
Have you looked at https://bcm-uga.github.io/pcadapt/articles/pcadapt.html#g--detecting-local-adaptation-with-pooled-sequencing-data?

**Comment by HengLiang1993** [comment]
Hi
Yes, but my sequence is capture-Seq data, not the Pool-Seq data, and can it also apply？

**Comment by privefl** [comment]
I have no idea what that is, sorry.
Is this a matrix of allele frequencies for many variants across multiple populations?
If so, I think that's basically the same.

**Comment by HengLiang1993** [comment]
It is the matrix of allele frequencies for many variants across multiple individuals in per population (10 individuals in per population to calculate the allele frequencies).

**Comment by privefl** [comment]
Did you try it?
