### ISSUE TITLE
PCADAPT error when higher K - can't compute SVD

### ISSUE THREAD

**Issue by GabryS3** [bcm-uga/pcadapt#84]
Dear Florian,
I am just exploring now for the first time your package pcadapt.

It seemed to run perfectly until I wanted to retain up to K=150, but if I try to retain 200 PCs or above, it gives me the following error:

<
**Error: Can't compute SVD.
Are there SNPs or individuals with missing values only?
You should use PLINK for proper data quality control.**
>

I don’t quite understand this message: my dataset was filtered with locus CR >0.97, Reproducibility >0.98, a good read depth cutoff eliminating the tail of the distribution and MAF>0.05. Individual CR is >0.98. So missingness is quite low in general.
In addition, prior to converting the genlight dataset (package dartR) into a lfmm file format for pcadapt, I removed all NAs in the dataset (with a dartR function which deletes loci or individuals with all calls missing, that is all NAs).
Could you help me understand what is the problem?

The reason why I wanted to run pcadapt retaining a higher number of PCs is that in my screeplot the curve of PCs keeps descending smoothly without a clear cutoff point/drop where the PCs start to seem to be explaining random noise (no horizontal line on the x axis).
So I cannot use Cattel’s rule to chose the number of PCs to retain, and I thought that if I increase the number of PCs retained I may be able to find the cutoff point. 
Do you think that, given that the variance explained by the PCs decreases slowly without a clear drop in the curve, is it helpful if I try run pcadapt retaining way more PCs?

I would appreciate any feedback on this.

Thank you for your kind assistance.
Best,
Gabriella

**Comment by privefl** [comment]
- What is the size of your dataset?
- Which `packageVersion("pcadapt")` do you have?
- Could you show the screeplot? (just drag&drop the figure here)

**Comment by GabryS3** [comment]
Dear Florian,
thank you for your reply.

See my replies in red to your questions below:

Il giorno gio 4 gen 2024 alle ore 17:34 Florian Privé <
***@***.***> ha scritto:

>
>    - What is the size of your dataset?
>
> n Loci = 9529, n Indiv = 182

>
>    - Which packageVersion(pcadapt) do you have?
>
> packageVersion("pcadapt") # ‘4.3.3’

>
>    - Could you show the screeplot? (just drag&drop the figure here)
>
>  PCADAPT # 1 - kept K=100
[image: image.png]
PCADAPT #2 - kept K=50
--> plot K=50


[image: b8c9d61a-ebf6-4f0b-94c4-a2c9f6f29f28.png]


 PCADAPT #2 - kept K=50
--> plot K=10
[image: image.png]
Also, the Manhattan plot changes quite a bit if I retain 50, 10 or 2 K in
pcadapt, showing a more homogeneous distribution of values/dots, with fewer
dots standing far away from the rest.
With K=50, I get 96 outliers with BH-FDR and 7 with Bonferroni, while I get
0 outliers with K=10 or K=2 (in both BH and Bonferroni).
Plus, in the QQplot, the expected p-values get much closer to the observed
p-values gradually from K=50 to K=10, K=2.
And the distribution of the D statistics is similar in K=50 and K=10,
resembling a normal distribution with a long right tail, while in K=2 the
distribution looks like a chi-square distribution starting at 0 with a
right skewed distribution of values (right tail only).

Does this mean I should be keeping K=2 only?

Thank you so much for your feedback.
Best,
Gabriella

**Comment by privefl** [comment]
I do not see the figures. I think you should reply on GitHub instead of in the email directly.

**Comment by GabryS3** [comment]
Dear Florian,
thank you for your reply.

See my replies in bold to your questions below:

What is the size of your dataset?
**n Loci = 9529, n Indiv = 182** 
Which packageVersion(pcadapt) do you have?
**packageVersion("pcadapt") # ‘4.3.3’** 
Could you show the screeplot? (just drag&drop the figure here)
 **PCADAPT # 1 - kept K=100**

![image](https://github.com/bcm-uga/pcadapt/assets/109197540/686a772e-8ed4-40ad-bcb2-d2ad69922ff4)


PCADAPT #2 - kept K=50
--> plot K=50


![image](https://github.com/bcm-uga/pcadapt/assets/109197540/501d4b51-c00b-41ff-9648-09b437c9f1d2)


 PCADAPT #2 - kept K=50
--> plot K=10

![image](https://github.com/bcm-uga/pcadapt/assets/109197540/68744e95-5321-4872-a0f6-e974aa152a54)


Also, the Manhattan plot changes quite a bit if I retain 50, 10 or 2 K in pcadapt, showing a more homogeneous distribution of values/dots, with fewer dots standing far away from the rest.
With K=50, I get 96 outliers with BH-FDR and 7 with Bonferroni, while I get 0 outliers with K=10 or K=2 (in both BH and Bonferroni).
Plus, in the QQplot, the expected p-values get much closer to the observed p-values gradually from K=50 to K=10, K=2.
And the distribution of the D statistics is similar in K=50 and K=10, resembling a normal distribution with a long right tail, while in K=2 the distribution looks like a chi-square distribution starting at 0 with a right skewed distribution of values (right tail only).

Does this mean I should be keeping K=2 only?

Thank you so much for your feedback.
Please let me know if you can see the figures now..
Best,
Gabriella

**Comment by privefl** [comment]
Ok, the main issue here is that you ask for K=200 PCs, but the minimum dimension is 182, so that's not possible.
In the latest version of the package (which is on CRAN), you should get a more informative error about this.

From the screeplots you show, I would pick either K=1 or K=5, or something close. To chose K, I would visualize first PC scores (say k=1:8) and decide where there seems to be some population structure (it is even better if you know the different populations, and can color PC scores by them).

**Comment by GabryS3** [comment]
Oh, ok thanks. I thought there should be as many PCs as there are SNPs.
Yes, thank you. I did plot by various PCs and color by population and no clustering/pattern shows up in the data. So, I am assuming it's ok for me to chose K=2.
Thank you again! That was really helpful!
Best,
Gabriella
