### ISSUE TITLE
can not change Manhattan plot color

### ISSUE THREAD

**Issue by WWz33** [bcm-uga/pcadapt#85]
Dear all,
`pcadapt_plot=plot(x, option = "manhattan",col ="orange")
`

![image](https://github.com/bcm-uga/pcadapt/assets/102402699/aefa477e-65dd-483a-b460-e1899d05d1d3)
Best ！

**Comment by privefl** [comment]
Hey what's the issue?

**Comment by WWz33** [comment]
Hi all,
Thanks for the reply. I would like to know how to change the color of the Manhattan plot.

**Comment by privefl** [comment]
This is a ggplot. Just learn more about this.
