### ISSUE TITLE
Low explained Variance after LD clumping

### ISSUE THREAD

**Issue by mehakmadhura** [bcm-uga/pcadapt#87]
Hii,
I had a question about LD clumping. I observed that in a PCA done with LD clumping, the percentage of variance explained by the PCs is much lower than that explained by PCs without clumping. Can you please explain the reason?

**Comment by privefl** [comment]
Could you give actual numbers and plots

**Comment by mehakmadhura** [comment]
Hii!
Thank you for your reply.
Here are the scree plots with and without clumping.
![screeplot_un_clump1000](https://github.com/bcm-uga/pcadapt/assets/109357651/b3c5901e-c0ea-42e0-b4dc-dac1ceec52bf)
![screeplot_un_ld_prunned](https://github.com/bcm-uga/pcadapt/assets/109357651/caf366d5-6222-4534-ab5f-677af8683658)

The proportion of explained variance is lower in the first plot with clumping.

**Comment by privefl** [comment]
I guess we expect some minor drop in variance explained, just because there are less variables used.
However, I do not think we expect such a large drop indeed, especially if population structure is captured.

- What is the proportion of variables removed/kept after clumping?
- Could you show the first two PC scores in both cases

**Comment by mehakmadhura** [comment]
I think it keeps around 0.6 of the variants.
Here are the PC scores for clumping and no clumping
![scores12_un_k3_clump1000](https://github.com/bcm-uga/pcadapt/assets/109357651/a0a9a505-7c16-4e0c-b01d-d08757e47974)
![scores12_un_ld_prunned](https://github.com/bcm-uga/pcadapt/assets/109357651/5442214f-9fce-4da4-96b1-f23a0da3e45e)

Also, when we decide on a k, for example, k=3. does pcadapat perform a PCA again with k-3, or just select the first 3 pcs for computation?

**Comment by privefl** [comment]
- It keeps 60% of variants? Or 0.6%?

- The PC scores seem highly similar, which is expected. So I don't get why there is such a large difference in the proportion of variance explained; it may simply due to an error in the way it is computed.

- pcadapt does the computation from scratch every time, bu it should be quite fast.

**Comment by mehakmadhura** [comment]
Thank you for your replies. It keeps 60% of the variants.
Also, does it show such a decrease in the variance explained for other datasets as well?

**Comment by privefl** [comment]
These are the results from the tutorial:

![unnamed-chunk-17-1](https://github.com/bcm-uga/pcadapt/assets/11161036/6566c230-9dc2-4c19-8d05-9d57261f5348)

![unnamed-chunk-20-1](https://github.com/bcm-uga/pcadapt/assets/11161036/a2f22284-5b0b-42e2-83b7-8524259f242f)

So, I guess, yes.

I'll try to see if there is better way to estimate these.

**Comment by mehakmadhura** [comment]
Thank you so much!

**Comment by privefl** [comment]
I've implemented a better estimate of the total variance to get better estimates of the proportions of explained variance. 
But I still get very similar results for the tutorial.

Can you try the latest GitHub version on your data?

**Comment by mehakmadhura** [comment]
Hii!
Thanks for the update. I tried the new version on my dataset. I have attached the screeplots with and without clumping.
![test_french_clump1000_new4 4](https://github.com/bcm-uga/pcadapt/assets/109357651/fe288283-d548-494a-a830-008e4dc0202a)
![test_french_noclump_new4 4](https://github.com/bcm-uga/pcadapt/assets/109357651/ed42bfec-f5c5-414f-a982-b0112cecf3c5)

**Comment by privefl** [comment]
What do you get for `sum(!is.na(x$loadings[, 1])) / length(x$pass)`?

**Comment by mehakmadhura** [comment]
0.03581412 with clumping and 1.050497 without clumping.
Also, this is with k=10. I didn't choose for a K yet.

**Comment by privefl** [comment]
Okay, this should be the percentage of variants (that passed the MAF threshold) kept after clumping.
So this is a very small percentage that is kept. This may explain the results.
I would have expected you would get 1 without the clumping however.

**Comment by mehakmadhura** [comment]
Oh! So is the fraction of explained variance by the PCs with respect to the variance of whole data, and not with respect to just the subset left after clumping?

**Comment by privefl** [comment]
Yes, the total variance is computed from the data after the MAF threshold.

**Comment by mehakmadhura** [comment]
Okay. Thank you so much for your prompt replies!

**Comment by privefl** [comment]
Are you happy with this?
Should we close this issue?

**Comment by mehakmadhura** [comment]
Yes Sure! Thank you so much.
