### ISSUE TITLE
Eigenvalues and pcadapt for pooledSeq

### ISSUE THREAD

**Issue by mroesti** [bcm-uga/pcadapt#88]
I have three questions concerning pcadapt.

1) How can I extract the eigenvalues (i.e., contribution of each PC axis to the total variance explained)? I found the option to plot these values as screeplot, but I didn't figure out how to extract the actual values.

2) Pcadapt can also be used to analyze pooled-seq data to find signatures of adaptation. 

2.1 The way I interpret your description is that the input data would in this case be relative allele frequencies. Just to make clear I'm correct, here an example: let's say I pool-sequenced each of two populations (A and B) with 100x at one biallelic locus. Let's say I have 20 x A and 80 x C base calls for population A, and 60 x A and 40 x C base calls for population B. The input data for pcadapt for this locus would then be 0.2 (or 0.8) for population A and 0.6 (or 0.4) for population B. Correct? 

2.2 If I had whole-genome pooled-seq data from only two populations, would you still think that using pcadapt is useful and possibly more powerful to find signatures of divergent selection between these two populations than, say, normal Fst-based divergence scans? 

Thanks a lot for your help and inputs!

**Comment by privefl** [comment]
- The proportion of variance explained by each PC is `x$singular.values^2`
- Correct for the frequencies
- If you have many samples but really only have two populations, then the scree plot and PC plot should suggest using K=1, and you should have very similar results as with Fst. If you have only pooled-seq data with only two lines, then maybe pcadapt is not needed.

**Comment by mroesti** [comment]
Thanks!!
