### ISSUE TITLE
Can I use PCAadapt even if I don't have population structure?

### ISSUE THREAD

**Issue by marce-herrera** [bcm-uga/pcadapt#91]
Hello,

I have a dataset consisting of 40 individuals, with 20 individuals from each of two putative populations. Preliminary analyses suggest that these two populations are not significantly different from each other. However, I am interested in determining whether it is still possible to identify any adaptive loci despite the lack of population structure. Would it make sense to pursue this analysis, and if so, can this be achieved using PCAadapt?

Thank you!

**Comment by privefl** [comment]
What do you see on the first two PCs?

**Comment by marce-herrera** [comment]
Hi,

Thank you for getting back so fast! 

As you can see below, there's no structure..

![Screen Shot 2024-06-24 at 15 32 01](https://github.com/bcm-uga/pcadapt/assets/173646331/00c9848c-6cbe-4cb4-bd74-1524284d0344)
![Screen Shot 2024-06-24 at 15 32 55](https://github.com/bcm-uga/pcadapt/assets/173646331/0c9fc6b3-a0af-431e-ad97-b0ff6079ff39)

This is the screeplot:
![Screen Shot 2024-06-24 at 15 33 16](https://github.com/bcm-uga/pcadapt/assets/173646331/7fc78d1b-19ba-4baf-9547-1f7392ae61c5)

**Comment by privefl** [comment]
Then I guess you won't get much from pcadapt.
Is the Manhattan plot flat?

**Comment by marce-herrera** [comment]
Hi there,

See the plots below for k = 10
![Screen Shot 2024-06-24 at 16 18 07](https://github.com/bcm-uga/pcadapt/assets/173646331/7add5163-3215-4c50-a770-4607895caa71)

![Screen Shot 2024-06-24 at 16 39 59](https://github.com/bcm-uga/pcadapt/assets/173646331/40d81e98-3221-40d8-9c61-e8a3cc240e21)

Thanks!

**Comment by privefl** [comment]
The PCA here probably captures LD structure only; you need to use some clumping.

**Comment by marce-herrera** [comment]
Hello,

I did the LD clumping (as shown in the tutorial) and this is what I get:

![Screen Shot 2024-06-24 at 17 44 40](https://github.com/bcm-uga/pcadapt/assets/173646331/b2106e30-4da0-4f7d-bf9a-34ac31fe5aa7)

This is for k=10 (same as before):
![Screen Shot 2024-06-24 at 17 44 22](https://github.com/bcm-uga/pcadapt/assets/173646331/5ae94e6a-edf2-41a4-a44a-86e20c5ea216)
![Screen Shot 2024-06-24 at 17 46 40](https://github.com/bcm-uga/pcadapt/assets/173646331/898bf7d4-bc8b-4c2f-817b-0d7d9174d87e)
![Screen Shot 2024-06-24 at 17 46 47](https://github.com/bcm-uga/pcadapt/assets/173646331/483e3f05-0cbc-4ae2-955e-1f6c68752890)

I'm not really sure how to interpret this. Any advice?

Thank you!

**Comment by privefl** [comment]
I would interpret this as: you need even more clumping (smaller r2 threshold). 
If you still get something similar, I think you can give up.

**Comment by marce-herrera** [comment]
Hi,

So this time I used LD.clumping = list(size = 200, thr = 0.1)

Do you think doing size=500 or size=1000 will make a difference? by smaller r2 threshold you mean ...? thr = 0.05, thr = 0.01?

Thanks!

**Comment by privefl** [comment]
It seems you have very long-range LD regions.
You can try e.g. size = 1e5 and thr = 0.02.

**Comment by marce-herrera** [comment]
Hello,

Here's an update: 

After reviewing my progress, I realized that I had not performed LD pruning on my SNP dataset. I went back and completed this step using PLINK. 

Afterward, I ran PCAdapt and obtained the following results:

x <- pcadapt(input = filename, K = 20)
plot(x, option = "screeplot")
![Screen Shot 2024-06-25 at 16 12 14](https://github.com/bcm-uga/pcadapt/assets/173646331/d14a97aa-b3c3-4140-b1f0-b288c660e146)

poplist.names <- c(rep("lagoon", 20), rep("ocean", 20))
plot(x, option = "scores", pop = poplist.names)
![Screen Shot 2024-06-25 at 16 12 54](https://github.com/bcm-uga/pcadapt/assets/173646331/c82dc90b-2141-492b-917a-1f3503b71d05)
![Screen Shot 2024-06-25 at 16 13 07](https://github.com/bcm-uga/pcadapt/assets/173646331/c1ddea1b-9257-491b-bfd7-be612c4e7cbe)

par(mfrow = c(2, 2))
for (i in 1:4)
  plot(x$loadings[, i], pch = 19, cex = .3, ylab = paste0("Loadings PC", i))
![Screen Shot 2024-06-25 at 16 13 52](https://github.com/bcm-uga/pcadapt/assets/173646331/dd9d2aa7-0858-495c-b729-6a876e7af9e4)

Based on the first screeplot I chose k = 5:
x <- pcadapt(filename, K = 5)
plot(x , option = "manhattan")
![Screen Shot 2024-06-25 at 16 14 44](https://github.com/bcm-uga/pcadapt/assets/173646331/0b5aad65-f556-46c5-9393-d68aa6423a2f)
(You can still see a peak, but it's much better than it was before I did the pruning.)

plot(x , option = "qqplot")
![Screen Shot 2024-06-25 at 16 15 42](https://github.com/bcm-uga/pcadapt/assets/173646331/58f0744b-b89c-46fc-b547-14a62c3646d5)

hist(x$pvalues, xlab = "p-values", main = NULL, breaks = 50, col = "orange")
![Screen Shot 2024-06-25 at 16 16 14](https://github.com/bcm-uga/pcadapt/assets/173646331/f264a2c8-f234-4b9d-a801-1aa22738e063)

plot(x, option = "stat.distribution")
![Screen Shot 2024-06-25 at 16 16 53](https://github.com/bcm-uga/pcadapt/assets/173646331/9ccb689f-0cd8-4e14-a4eb-0df5a6687acd)

Because I still have high LD I did LD clumping as follows:
newx <- pcadapt(filename, K = 20, LD.clumping = list(size = 200, thr = 0.1))
plot(newx, option = "screeplot")
![Screen Shot 2024-06-25 at 16 18 04](https://github.com/bcm-uga/pcadapt/assets/173646331/508d9970-faa6-4e6d-9f9c-bf17cc904c8f)

newx <- pcadapt(filename, K = 5, LD.clumping = list(size = 200, thr = 0.1))

par(mfrow = c(2, 2))
for (i in 1:4)
  plot(newx$loadings[, i], pch = 19, cex = .3, ylab = paste0("Loadings PC", i))
![Screen Shot 2024-06-25 at 16 18 47](https://github.com/bcm-uga/pcadapt/assets/173646331/39259acf-1cbf-4ef9-adbe-a890d0a87842)

plot(newx , option = "manhattan")
![Screen Shot 2024-06-25 at 16 19 26](https://github.com/bcm-uga/pcadapt/assets/173646331/b0a52763-61f4-4b7b-8423-a9dfc08c503f)

plot(newx , option = "qqplot")
![Screen Shot 2024-06-25 at 16 19 49](https://github.com/bcm-uga/pcadapt/assets/173646331/45e045c4-7f26-4dd5-b25f-957b76e16285)

hist(newx$pvalues, xlab = "p-values", main = NULL, breaks = 50, col = "orange")
![Screen Shot 2024-06-25 at 16 20 25](https://github.com/bcm-uga/pcadapt/assets/173646331/b42eda3e-42df-48c5-8106-3f25b224b957)

plot(newx, option = "stat.distribution")
![Screen Shot 2024-06-25 at 16 20 35](https://github.com/bcm-uga/pcadapt/assets/173646331/3a5f374d-7ef9-4ec3-81cb-86b2bdbc6d3c)

I then get ~1200 outliers:
padj <- p.adjust(newx$pvalues,method="BH")
alpha <- 0.05
bh_outliers <- which(padj < alpha)
length(bh_outliers)
[1] 1216

Do you think this approach is correct? Am I right in understanding that these 1,216 outliers are adaptive loci? What does this imply even if I don't initially observe population structure? How can I retrieve these outliers? I am interested in analyzing them further with SNP effect to see the functional effect...

Thank you again!!

**Comment by privefl** [comment]
No, I'm afraid you're still capturing only LD.
There is no visible population structure.

**Comment by marce-herrera** [comment]
Right, okay. Just to clarify, is PCAdapt only useful if there is population structure? If so, I cannot use it with this dataset... correct?

**Comment by privefl** [comment]
Yes x2

**Comment by marce-herrera** [comment]
Ok, thank you!

One last question (sorry if it seems simple, I'm new to population genetics). Can you recommend other tools for detecting outliers? Is it worth pursuing this if I don't have population structure data? My reasoning is that I might not have enough differences to detect population structure, but I could still find differences at certain loci, which I would be interested in exploring.

Thanks again!

**Comment by privefl** [comment]
I'm not really an expert in popgen either, sorry.
